## Pytest and exception

You can check with pytest whether a function has raised an exception, per [this](docs.pytest.org/en/latest/how-to/assert.html#assertions-about-expected-exceptions)
